version: 1
disable_existing_loggers: False

formatters:
  console:
    "()": uvicorn.logging.DefaultFormatter
    format: "%(levelprefix)s %(message)s"
    use_colors: true

  file:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: file
    filename: logs/app.log
    maxBytes: 10485760   # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  uvicorn:
    level: INFO
    handlers: [console, file]
    propagate: False

  uvicorn.error:
    level: INFO
    handlers: [console, file]
    propagate: False

  uvicorn.access:
    level: INFO
    handlers: [console, file]
    propagate: False

  watchfiles:
    level: WARNING
    handlers: [console]
    propagate: False

root:
  level: INFO
  handlers: [console, file]
